
user  www-data;
#how  many  work  process one  per  cpu 
worker_processes auto ;

# how  nginx  handles  conections each  worker  can handle  1024  connectios at  same time
events  {
     worker_connections 1024;
}
# without  that  block  browser  doesnt know  how to  handle  files

#the  protovol using  when  the  request has  been  recieved  by  the nginx
http
{
    include  /etc/nginx/mime.types;
    # if  file type   unknown -<  treat  it  as  binary  download
    default_type  application/octet-stream;
    #server  just a config  tell  nginx  how  to  handle  request should  be  on that  block of  https cause  its  need  her  parent  handle  trafic
    server
    {
    #telling  nginx  wich  door  to  stand  at  and wait  for  visitors
            listen  443 ssl;

            #the  name_tag for the server
            server_name  moouhida.42.fr;

            #block  all the  older  insecured protocols 
            ssl_protocols    TLSv1.2 TLSv1.3;

            #the  public  certificate (shared with  every one)
            ssl_certificate  /etc/nginx/ssl/nginx.crt;

            #private key(never shared)
            ssl_certificate_key /etc/nginx/ssl/nginx.key;

            #wher  you file  are(telling  the ngix where  to  look  for  the  webdite files)
            root   /var/www/html;

            #default  files (welcome  pages)
            index index.php  index.html;

            location / {
                #try  the  exact  file  resuest   then  try  it as a folder if nothing found send it to wordpress
                try_files $uri $uri/ /index.php?$args;
            }
            #the nginx  forward  the request  to the  wordpress
            location ~ \.php$ {
                #sends PHP  resuest to  the  wordpress  conatainer (why  9000  cuase  word press container  runs php-fpm and  he  listen  onport  9000  by  default)
                fastcgi_pass wordpress:9000;
                #standard  parametrs nginx sends  along
                fastcgi_index index.php;
                #a file  that already exist  an d conatain  the metadat  about  the request  that  PHP needs  to  process it
                include fastcgi_params;
                #tell the  wordpress exctly  which  PHP files  to run
                fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            }
    }

}