version: '3'


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentails:
    file : ../secrets/credentials.txt

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    env_file :
      - .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart  : always
  wordpress :
    build:  ./requirements/wordpress
    container_name:    wordpress
    env_file :
      - .env
    secrets :
      - db_password
      - credentails
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
    restart : always
  nginx :
    build: ./requirements/nginx
    container_name: nginx
    ports :
     - "433:433"
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on :
     -  wordpress
    restart : always

networks:
  inception :
    driver :  bridge

volumes:
  db_data:
    driver: local
    driver_opts :
      type : none
      o : bind
      device  : /home/moouhida/data/mysql
  wp_data :  
      driver :  local
      driver_opts :
        type :  none
        o : bind
        device  : /home/moouhida/data/wordpress

#driver  :  local
#told  the docker where to save  the  data(other  option  it can  be stored  on : nfs tmpfs s3 azure (another  mashine via ssh))
#and  device the exact  path  were  data  get  saved
#type  none  type  of  filesystem  (how  to  read and  write data)
#we confirm it with none cuaseteh  file already exisct  and  created  by  makefile so  the  filesystem already exist
#o =  option  bind ->  defualt  for read  and write  its  just permission  for  that file