[www]
#her we define wish  linux  user  to  run  php-fpm
#why ?
#if  php-hacked the scammer cant  touch  the  system file cannot  ddestroy  server only he  will become www-data
# www-data  a spectial  user  created by  debian  for  web  servers
user = www-data

#define  which  group that php-fpm belong  to it
#nginx and  wordpress  share the same group  so  they  can share  data
group = www-data
#tell php-fpm wher  to listen for  request 
#0.0.0.0  listen  on all  network  interface
listen = 127.0.0.1:9000
#0.0.0.0 mains  accept connnection from  any ip
#adress /container/any network
#why not  127.0.0.1 localhost only accept  from same container 
#and  nginx  are different container cannot  reach  it then

#define   the  who  own  the listenign socker
#must  match nginx  user  to connect 
#if thery  are  different user cannot  listen (www-data)
listen.owner  = www-data
listen.group = www-data

#pm process manager control  how  php=fpm  manage its  workers
#dynamic
#pm  has 3 modes (1static  2dynamic  3ondemand )  
pm = dynamic

#maximum  number  of worker processes allowed(the  number of  request  can handle at  once)
pm.max_children  = 5

#number ofworker  that  start  immedialtly  when  php-fom  starts
pm.start_servers = 2

#idle to wait for  reuest  for  fast respond
pm.min_spare_servers = 1 

pm.max_spare_servers = 3
