#standalone to  listen  for  connections alone
pam_service_name=vsftpd
background=NO
listen=YES
listen-ipv6=NO
anonymous_enable=NO
#allow allow linux user to login as we create an use an user in wordpres .sh 
local_enable=YES
write_enable=YES
local_umask=022
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty
pasv_enable=YES
pasv_min_port=30000
pasv_max_port=30010